--- 
abstract: GUI frontend for PAR::Dist::InstallPPD
author: Steffen Mueller (smueller@cpan.org)
build_requires: 
  ExtUtils::MakeMaker: 6.11
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: PAR-Dist-InstallPPD-GUI
no_index: 
  directory: 
    - inc
    - t
requires: 
  Config::IniFiles: 0
  ExtUtils::Install: 0
  File::UserConfig: 0
  IO::Dir: 0
  IPC::Run: 0.80
  PAR::Dist::FromPPD: 0.02
  PAR::Dist::InstallPPD: 0.01
  Tk: 0
  Tk::Dialog: 0
  Tk::ROText: 0
  perl: 5.6.0
version: 0.05
